num_strings: 7
num_frets: 24
string_tunings:
  - A
  - E
  - A
  - D
  - G
  - B
  - E

scales:
  Ionian:
    - 2
    - 2
    - 1
    - 2
    - 2
    - 2
    - 1

  Dorian:
    - 2
    - 1
    - 2
    - 2
    - 2
    - 1
    - 2

  Phrygian:
    - 1
    - 2
    - 2
    - 2
    - 1
    - 2
    - 2

  Lydian:
    - 2
    - 2
    - 2
    - 1
    - 2
    - 2
    - 1

  Mixolydian:
    - 2
    - 2
    - 1
    - 2
    - 2
    - 1
    - 2

  Aeolian:
    - 2
    - 1
    - 2
    - 2
    - 1
    - 2
    - 2

  Locrian:
    - 1
    - 2
    - 2
    - 1
    - 2
    - 2
    - 2

  harmonic_major:
    - 2
    - 2
    - 1
    - 2
    - 1
    - 3
    - 1

  harmonic_minor:
    - 2
    - 1
    - 2
    - 2
    - 1
    - 3
    - 1